// <auto-generated />
using System;
using FootballChampionship;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FootballChampionship.Migrations
{
    [DbContext(typeof(Program.FootballChampionship8))]
    [Migration("20210125144528_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("FootballChampionship.Program+FootballTeams", b =>
                {
                    b.Property<int>("FootballTeamsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("FootballTeamName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FootballTeamsId");

                    b.ToTable("FootballTeams");
                });

            modelBuilder.Entity("FootballChampionship.Program+Matches", b =>
                {
                    b.Property<int>("MatchesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int?>("FirstTeamFootballTeamsId")
                        .HasColumnType("int");

                    b.Property<int>("GoalsScoredByFirstTeam")
                        .HasColumnType("int");

                    b.Property<int>("GoalsScoredBySecondTeam")
                        .HasColumnType("int");

                    b.Property<int?>("SecondTeamFootballTeamsId")
                        .HasColumnType("int");

                    b.HasKey("MatchesId");

                    b.HasIndex("FirstTeamFootballTeamsId");

                    b.HasIndex("SecondTeamFootballTeamsId");

                    b.ToTable("Matches");
                });

            modelBuilder.Entity("FootballChampionship.Program+Ranks", b =>
                {
                    b.Property<int>("RanksId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("ChampionshipPoints")
                        .HasColumnType("int");

                    b.Property<int>("Place")
                        .HasColumnType("int");

                    b.Property<int?>("TeamFootballTeamsId")
                        .HasColumnType("int");

                    b.HasKey("RanksId");

                    b.HasIndex("TeamFootballTeamsId");

                    b.ToTable("Ranks");
                });

            modelBuilder.Entity("FootballChampionship.Program+Matches", b =>
                {
                    b.HasOne("FootballChampionship.Program+FootballTeams", "FirstTeam")
                        .WithMany()
                        .HasForeignKey("FirstTeamFootballTeamsId");

                    b.HasOne("FootballChampionship.Program+FootballTeams", "SecondTeam")
                        .WithMany()
                        .HasForeignKey("SecondTeamFootballTeamsId");

                    b.Navigation("FirstTeam");

                    b.Navigation("SecondTeam");
                });

            modelBuilder.Entity("FootballChampionship.Program+Ranks", b =>
                {
                    b.HasOne("FootballChampionship.Program+FootballTeams", "Team")
                        .WithMany()
                        .HasForeignKey("TeamFootballTeamsId");

                    b.Navigation("Team");
                });
#pragma warning restore 612, 618
        }
    }
}
